version: "3.7"

volumes:
  boilerplatevolume:
    name: boilerplate-volume

networks:
  boilerplatenetwork:
    name: boilerplate-network

services:
  boilerplate_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    networks:
      - boilerplatenetwork
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]